### ISSUE TITLE
[feature requested] Tiling: detect and skip pre-existing patches during new execution of tiling if previous raised error

### ISSUE THREAD

**Issue by remtav** [NRCan/geo-deep-learning#428]
The tiling script frequently raises errors on large datasets. 
Two solutions could help preventing the long re-execution of this process for the same dataset: 
- add more try/except statements to proceed with tiling even if a particular AOI has raised an error
- during re-execution, detect and skip existing patches, i.e. append new patches to existing.

Here's an example of an error I just encountered:
```python
Error executing job with overrides: ['mode=tiling', 'dataset.raw_data_csv=/gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/models/single/RGB/Building/3provs/training_set_NB-NFL-QC_building_ids.csv', 'dataset.raw_data_dir=/gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/operationalization/data', 'dataset.attribute_field=Quatreclasses', 'dataset.attribute_values=[4]', 'dataset.download_data=True', 'tiling.tiling_data_dir=/gpfs/fs5/nrcan/nrcan_geobase/work/transfer/work/deep_learning/models/single/RGB/Building/3provs/patches', 'tiling.multiprocessing=True', 'tiling.patch_size=512', 'verify.output_raster_plots=False', 'verify.output_raster_stats=False', 'verify.extended_label_stats=False', 'general.project_name=3provs_NB-NFL-QC_building', 'debug=False']
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/space/partner/nrcan/geobase/work/opt/miniconda-gdl-ops/envs/geo_deep_env/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/space/partner/nrcan/geobase/work/opt/miniconda-gdl-ops/envs/geo_deep_env/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 519, in map_wrapper
    return x[0](*(x[1:]))
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 490, in filter_and_burn_dataset
    min_annot_success, annot_perc = self.passes_min_annot(
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 370, in passes_min_annot
    annot_perc = annot_percent(
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/tiling_segmentation.py", line 50, in annot_percent
    gdf_patch_bounds, img_patch_bounds = bounds_gdf(gdf_patch), bounds_riodataset(img_patch_dataset)
  File "/fs/vnas_Hnrcan/geobase/ret000/geo-deep-learning/utils/geoutils.py", line 214, in bounds_gdf
    gdf_bounds_box = box(*gdf_bounds.tolist())
  File "/space/partner/nrcan/geobase/work/opt/miniconda-gdl-ops/envs/geo_deep_env/lib/python3.10/site-packages/shapely/geometry/geo.py", line 64, in box
    return Polygon(coords)
  File "/space/partner/nrcan/geobase/work/opt/miniconda-gdl-ops/envs/geo_deep_env/lib/python3.10/site-packages/shapely/geometry/polygon.py", line 261, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/space/partner/nrcan/geobase/work/opt/miniconda-gdl-ops/envs/geo_deep_env/lib/python3.10/site-packages/shapely/geometry/polygon.py", line 539, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 413, in shapely.speedups._speedups.geos_linearring_from_py
ValueError: GEOSGeom_createLinearRing_r returned a NULL pointer
"""
```

As can be seen, the error was raised during the 2nd for loop of tiling, meaning all patches from 1st for loop should be created and ok to reuse.

**Comment by ms888ekb** [comment]
Is it somewhere in your branch? I don't see this code in develop
